### ISSUE TITLE
about chromosome 8 centromere validation

### ISSUE THREAD

**Issue by zhoudreames** [glogsdon1/sunk-based_assembly#2]
in your article, the centromere assembly was validated by using winnowmap/pbmm2 software to gain uniform coverage,but in your 2020 article about chromosome X centromere coverage valiation by using uniq kmer assist mapping method.i dont konw what's different in the two method ? or the winnowmap/pbmm2 software was able to replace the uniq kmer assist mapping method ?

**Comment by zhoudreames** [comment]
@glogsdon1 could you help me ?

**Comment by glogsdon1** [comment]
Hi zhoudreames,

We were able to use winnowmap (for ONT) and pbmm2 (for HiFi) this time because the chr8 assembly is so much more accurate than the chrX assembly was at the time, and the reads mapped much more accurately to it with these tools. Our chr8 assembly is built mainly from HiFi contigs, which are typically >99.99% accurate. The chrX assembly was built from ONT contigs, which were then polished to improve the accuracy. However, it still ended up being less accurate than our chr8 assembly. Also, I should mention that the winnowmap software wasn't released until after the chrX paper came out, so it wasn't even an option to use at the time. If you are generating a HiFi-based genome, I would say you could use winnowmap and pbmm2 without the need for the unique k-mer-assisted mapping.

**Comment by zhoudreames** [comment]
thanks~
